create table labs.fav_genres (
	id int generated by default as identity 
	(start with 1 increment by 1) primary key,
	genre text
);

update labs.users 
set favorite_genre  = (
	select genre
	from labs.fav_genres
	where labs.users.id = labs.fav_genres.id
)

drop table labs.fav_genres 

create table geo (
    id int not null primary key, 
    id_parent int references geo(id),  
    name text
);

insert into geo
(id, id_parent, name) 
values
(1, null, 'Planet Earth '),
(2, 1, 'Continent Eurasia'),
(3, 1, 'Continent North America'),
(4, 2, 'Europe'),
(5, 4, 'Russia'),
(6, 4, 'Germany'),
(7, 5, 'Moscow'),
(8, 5, 'St. Petersburg'),
(9, 6, 'Berlin')

drop table labs.geo

create table friend (
	id int generated by default as identity 
	(start with 1 increment by 1) primary key,
	id_friend int
);

alter table labs.users add column id_friend int references labs.users(id);

update labs.users
set id_friend = (
	select labs.friend.id_friend 
	from labs.friend
	where labs.friend.id = labs.users.id 
)

drop table labs.friend 

alter table labs.users 
drop column id_friend;

select *
from labs.users
order by id
