CREATE SCHEMA labs

CREATE TABLE labs.users (
  id int generated by default as identity 
	(start with 1 increment by 1) primary key,
  nickname text not null,
  created_at timestamp not null,
  country text not null,
  email text not null,
  sex text
);

CREATE TABLE labs.studio (
  id int generated by default as identity 
	(start with 1 increment by 1) primary key,
  name text not null,
  headquarters text not null,
  founded date not null,
  employees int check (employees > 0),
  key_people text
);

CREATE TABLE labs.anime (
  id int generated by default as identity 
	(start with 1 increment by 1) primary key,
  title text not null,
  studio_id int not null references labs.studio (id),
  episodes int not null check (episodes > 0),
  mpaa text not null,
  start_at date not null,
  end_at date,
  rating float not null check (rating >= 0 and rating <= 10)
);

CREATE TABLE labs.viewed_anime (
	id int generated by default as identity 
	(start with 1 increment by 1) primary key,
	id_anime int not null references labs.anime (id),
	id_user int not null references labs.users (id),
	start_at timestamp not null,
	end_at timestamp not null check (end_at > start_at),
	rating int check (rating >= 0 and rating <= 10)
);
